#!/usr/bin/env python3
"""
MobileNetV3 Minimalistic Image Preprocessing Script for CFU-Playground

Converts images in images/ into a C header (image_inputs_mnv3.h) for
firmware use with the INT8-quantized MNv3-Small-Minimalistic model.

Key differences from the MNv2 preprocessor:
  - Target resolution: 160x160 (MNv3 model input, not 224x224)
  - Pixel encoding: signed INT8 [-128, 127] (quantized, zero-point=0, scale=1/128)
  - Output header:  common/src/models/mnv3/image_inputs_mnv3.h
"""

import os
import re
import numpy as np
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
IMAGE_DIR = os.path.join(PROJECT_ROOT, "images")
OUTPUT_HEADER = os.path.join(
    PROJECT_ROOT, "common", "src", "models", "mnv3", "image_inputs_mnv3.h"
)

# MNv3-Small-Min uses 160x160 INT8 input
TARGET_SIZE = (160, 160)
VALID_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp")


def sanitize_identifier(name: str) -> str:
    """Convert a filename stem into a valid C identifier."""
    clean = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if clean and clean[0].isdigit():
        clean = "_" + clean
    return clean


def preprocess_image_mnv3(img_path: str) -> np.ndarray:
    """
    Load an image and convert it to the INT8 representation expected by
    the quantized MNv3-Small-Min firmware model.

    MobileNetV3 preprocessing maps [0, 255] uint8 → [-128, 127] int8
    using: int8_value = uint8_value - 128
    (zero_point = 128, scale = 1/128 matches tf.int8 quantized export)
    """
    img = Image.open(img_path).convert("RGB").resize(TARGET_SIZE, Image.Resampling.LANCZOS)
    arr_uint8 = np.array(img, dtype=np.uint8).flatten()
    # Shift [0,255] → [-128,127]
    arr_int8 = arr_uint8.astype(np.int16) - 128
    return arr_int8.astype(np.int8)


def main():
    if not os.path.exists(IMAGE_DIR):
        print(f"Error: Directory '{IMAGE_DIR}' does not exist.")
        return

    image_files = sorted(
        f for f in os.listdir(IMAGE_DIR)
        if os.path.splitext(f)[1].lower() in VALID_EXTENSIONS
    )

    if not image_files:
        print(f"No image files found in '{IMAGE_DIR}'")
        return

    print(f"Found {len(image_files)} image(s): {image_files}")
    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)

    with open(OUTPUT_HEADER, "w") as f:
        f.write("/* Auto-generated by scripts/process_all_images_mnv3.py */\n")
        f.write("/* MobileNetV3-Small-Min: 160x160 INT8 input (zero_point=128) */\n")
        f.write("#ifndef _IMAGE_INPUTS_MNV3_H_\n")
        f.write("#define _IMAGE_INPUTS_MNV3_H_\n\n")
        f.write("#include <stdint.h>\n#include <stddef.h>\n\n")
        f.write("struct ImageSampleMnv3 {\n")
        f.write("    const char*    filename;\n")
        f.write("    const int8_t*  data;       /* 160*160*3 = 76800 INT8 bytes */\n")
        f.write("    size_t         size;\n")
        f.write("};\n\n")

        sample_entries = []

        for fname in image_files:
            img_path = os.path.join(IMAGE_DIR, fname)
            stem = os.path.splitext(fname)[0]
            var_name = "mnv3_img_" + sanitize_identifier(stem)

            raw_int8 = preprocess_image_mnv3(img_path)
            print(f"  Processed '{fname}': {len(raw_int8)} bytes → {var_name}")

            f.write(
                f"/* Image: {fname} ({TARGET_SIZE[0]}x{TARGET_SIZE[1]} RGB,"
                f" {len(raw_int8)} INT8 bytes) */\n"
            )
            f.write(f"static const int8_t {var_name}[] = {{\n")
            for i, b in enumerate(raw_int8):
                if i % 12 == 0:
                    f.write("    ")
                f.write(f"{int(b):4d}, ")
                if i % 12 == 11:
                    f.write("\n")
            f.write(f"\n}};\n\n")

            sample_entries.append((fname, var_name, len(raw_int8)))

        f.write("static const struct ImageSampleMnv3 ALL_IMAGES_MNV3[] = {\n")
        for fname, var_name, size in sample_entries:
            f.write(f'    {{"{fname}", {var_name}, {size}}},\n')
        f.write("};\n\n")
        f.write(f"#define NUM_IMAGES_MNV3 {len(sample_entries)}\n\n")
        f.write("#endif // _IMAGE_INPUTS_MNV3_H_\n")

    print(f"\nSuccessfully generated: {OUTPUT_HEADER}")
    print(f"Total images embedded:  {len(sample_entries)}")


if __name__ == "__main__":
    main()
