#!/usr/bin/env python3
import os
import re
import numpy as np
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, ".."))
IMAGE_DIR = os.path.join(PROJECT_ROOT, "images")
OUTPUT_HEADER = os.path.join(PROJECT_ROOT, "common", "src", "models", "mnv2", "image_inputs.h")

TARGET_SIZE = (224, 224)
VALID_EXTENSIONS = (".jpg", ".jpeg", ".png", ".bmp")

def sanitize_identifier(name):
    clean = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if clean and clean[0].isdigit():
        clean = "_" + clean
    return clean

def main():
    if not os.path.exists(IMAGE_DIR):
        print(f"Error: Directory {IMAGE_DIR} does not exist.")
        return

    image_files = sorted([
        f for f in os.listdir(IMAGE_DIR)
        if os.path.splitext(f)[1].lower() in VALID_EXTENSIONS
    ])

    if not image_files:
        print(f"No image files found in {IMAGE_DIR}")
        return

    print(f"Found {len(image_files)} image(s) in {IMAGE_DIR}: {image_files}")

    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)

    with open(OUTPUT_HEADER, "w") as f:
        f.write("/* Auto-generated by scripts/process_all_images.py */\n")
        f.write("#ifndef _IMAGE_INPUTS_H_\n")
        f.write("#define _IMAGE_INPUTS_H_\n\n")
        f.write("#include <stdint.h>\n#include <stddef.h>\n\n")
        f.write("struct ImageSample {\n")
        f.write("    const char* filename;\n")
        f.write("    const uint8_t* data;\n")
        f.write("    size_t size;\n")
        f.write("};\n\n")

        sample_entries = []

        for fname in image_files:
            img_path = os.path.join(IMAGE_DIR, fname)
            var_name = "img_data_" + sanitize_identifier(os.path.splitext(fname)[0])
            
            # Load, convert to RGB, and resize to 224x224
            img = Image.open(img_path).convert("RGB").resize(TARGET_SIZE)
            raw_bytes = np.array(img, dtype=np.uint8).flatten()

            f.write(f"/* Image: {fname} ({TARGET_SIZE[0]}x{TARGET_SIZE[1]} RGB, {len(raw_bytes)} bytes) */\n")
            f.write(f"static const uint8_t {var_name}[] = {{\n")
            for i, b in enumerate(raw_bytes):
                if i % 12 == 0:
                    f.write("\t")
                f.write(f"0x{b:02x}, ")
                if i % 12 == 11:
                    f.write("\n")
            f.write(f"\n}};\n\n")

            sample_entries.append((fname, var_name, len(raw_bytes)))

        f.write("static const struct ImageSample ALL_IMAGES[] = {\n")
        for fname, var_name, size in sample_entries:
            f.write(f'    {{"{fname}", {var_name}, {size}}},\n')
        f.write("};\n\n")
        f.write(f"#define NUM_IMAGES {len(sample_entries)}\n\n")
        f.write("#endif // _IMAGE_INPUTS_H_\n")

    print(f"Successfully generated database header: {OUTPUT_HEADER}")

if __name__ == "__main__":
    main()
